name: cs236781-tutorials
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # common
  - ipython
  - jupyter
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - pip
  - pytest
  - pytest-xdist
  - python=3.8.12
  - scikit-learn=1.1.3
  - scipy
  - tqdm
  # pytorch
  - pytorch
  - cudatoolkit
  - torchvision
  - torchtext
